### ISSUE TITLE
paylaşma aq

### ISSUE THREAD

**Issue by mercyxrd** [acarfx/acar-v13-bots#1]
ciddiyim paylaşma şu botlarını salıcaksanda sal dc yi, heryerde senin botlarını görmek istemiyorum anasını sikiceksin ortamın

**Comment by mercyxrd** [comment]
ya senin amına koyim pşlasdşlasşldşlal

**Comment by Tormund12** [comment]
> ya senin amına koyim pşlasdşlasşldşlal

Ekmeğimizle Oynama Hain Vatan HAİNİ 🍡

**Comment by okeados** [comment]
usta gelen gecen botcu oldu aminakoyim körükleme milleti la APSODKAPSODJAPDSOAJDPAODAPSDO

**Comment by acarfx** [comment]
ialişdqwlidqwişdlişqwldişlişLİLDQWİŞLDŞİQWLDİASDASİŞDASİŞLDAS xd şqidlişqwdiqwlşdliwqdliqwldqwl doğru diyonuz amk gelen geçen botçu olmuş dur daha qişdlqwşidl

**Comment by mercyxrd** [comment]
ĞWPQEĞPQWEĞPWQEPQWPĞ
