### ISSUE TITLE
acar sen nerde yaşıyon

### ISSUE THREAD

**Issue by bshvr1** [acarfx/acar-v13-bots#2]
acar bişe sorcam sen nerde yaşıyon benim burda bi adam var ayni sen aq

**Comment by bshvr1** [comment]
bu arada bişey daha sorcam ne zaman paylaşcan looo okullar açılcak okullar açılmadan botlari test edim

**Comment by bshvr1** [comment]
seviliyosün
sellahattin acar <3

**Comment by bshvr1** [comment]
amk adam yoldan geliyo ekmek almağa hergün sana benzetiyom amk

**Comment by mercyxrd** [comment]
malmısın amk

**Comment by acarfx** [comment]
QDİŞQLWİDWQŞDLŞQİWLDQLİDLQLDWQİLDİŞQWLDİLQWİDLQWİŞDLŞQ

**Comment by acarfx** [comment]
ankara kanka
